# -*- coding: utf-8 -*-
"""Aula_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVI_dXvXdRmTco864NUmTd7HqWiGC0aJ
"""



#Declare uma variável contendo uma frase. Em seguida, peça ao usuário para digitar uma palavra e concatene essa palavra no final da frase. Exiba o resultado.

# fra = "A linguagem de Programação:"


# pa = input("Cite uma linguagem de Programação:")

# print(f'{fra}{pa}')


# usuario = int(input('Digite um numero inteiro'))

# if usuario >0:
#   print('maior que zero')

# elif usuario ==0:
#   print('É zero')


# else:
#   print('menor que zero')


# exercício 2: Classificação de Triângulos

# Escreva um programa em Python que receba três comprimentos de lados de um triângulo e
# determine se o triângulo
# é equilátero, isósceles ou escaleno.

# lado1 = int(input('Digite um lado'))
# lado2 = int(input('Digite outro lado'))
# lado3 = int(input('Digite outro lado'))

# if lado1 ==  lado2 and lado2 == lado3:
#   print('Triangulo Equilatero')

# elif lado1 == lado2 or lado2 == lado3 or lado3 == lado1:

#   print('Triangulo Isosceles')

# elif lado1 != lado2 and lado2 != lado3 and lado3 != lado1:

#   print('Triangulo Escaleno')

# Exercício 3: Verificação de Ano Bissexto

# Um ano é bissexto se for divisível por 4, exceto para anos que são divisíveis por 100.
# No entanto, anos divisíveis por 400
# também são bissextos. Escreva um programa em Python que solicite um ano ao usuário
# e determine se é um ano bissexto ou não.


# ano = int(input('Digite o ano'))
# if(ano % 4 ==0 or ano % 100 ==0) or (ano % 400 ==0):
#   print('Ano bissexto')
# else:
#   print('Não é bissexto')

